// <auto-generated />
using System;
using MetalReleaseTracker.ParserService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetalReleaseTracker.ParserService.Infrastructure.Data.Migrations.ParserService
{
    [DbContext(typeof(ParserServiceDbContext))]
    [Migration("20260214145159_InitialParserService")]
    partial class InitialParserService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.AlbumParsedEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParsingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParsingSessionId");

                    b.ToTable("AlbumParsedEvents");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.ParsingSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DistributorCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PageToProcess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParsingStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ParsingSessions");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.AlbumParsedEventEntity", b =>
                {
                    b.HasOne("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.ParsingSessionEntity", "ParsingSession")
                        .WithMany()
                        .HasForeignKey("ParsingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParsingSession");
                });
#pragma warning restore 612, 618
        }
    }
}
