// <auto-generated />
using System;
using MetalReleaseTracker.ParserService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetalReleaseTracker.ParserService.Infrastructure.Data.Migrations.ParserService
{
    [DbContext(typeof(ParserServiceDbContext))]
    [Migration("20260223160516_AddSettingsTables")]
    partial class AddSettingsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Domain.Models.Entities.BandDiscographyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AlbumType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BandReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedAlbumTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BandReferenceId");

                    b.HasIndex("BandReferenceId", "NormalizedAlbumTitle")
                        .IsUnique();

                    b.ToTable("BandDiscography");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Domain.Models.Entities.BandReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MetalArchivesId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BandName");

                    b.HasIndex("MetalArchivesId")
                        .IsUnique();

                    b.ToTable("BandReferences");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Domain.Models.Entities.CatalogueIndexEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("BandReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedAlbumTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DistributorCode")
                        .HasColumnType("integer");

                    b.Property<int?>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BandReferenceId");

                    b.HasIndex("DetailUrl", "DistributorCode")
                        .IsUnique();

                    b.HasIndex("DistributorCode", "Status");

                    b.ToTable("CatalogueIndex");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Admin.Entities.AiAgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DelayBetweenBatchesMs")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentRequests")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("AiAgents");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Admin.Entities.AiVerificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AdminDecision")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AdminDecisionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AiAnalysis")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CatalogueIndexId")
                        .HasColumnType("uuid");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("CorrectedAlbumTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUkrainian")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueIndexId", "CreatedAt");

                    b.ToTable("AiVerifications");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Admin.Entities.ParsingSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistributorCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParsingUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistributorCode")
                        .IsUnique();

                    b.ToTable("ParsingSources");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Admin.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("Category");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.AlbumParsedEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParsingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParsingSessionId");

                    b.ToTable("AlbumParsedEvents");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.ParsingSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DistributorCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParsingStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ParsingSessions");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Domain.Models.Entities.BandDiscographyEntity", b =>
                {
                    b.HasOne("MetalReleaseTracker.ParserService.Domain.Models.Entities.BandReferenceEntity", "BandReference")
                        .WithMany("Discography")
                        .HasForeignKey("BandReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BandReference");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Domain.Models.Entities.CatalogueIndexEntity", b =>
                {
                    b.HasOne("MetalReleaseTracker.ParserService.Domain.Models.Entities.BandReferenceEntity", "BandReference")
                        .WithMany()
                        .HasForeignKey("BandReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BandReference");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Admin.Entities.AiVerificationEntity", b =>
                {
                    b.HasOne("MetalReleaseTracker.ParserService.Domain.Models.Entities.CatalogueIndexEntity", "CatalogueIndex")
                        .WithMany()
                        .HasForeignKey("CatalogueIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogueIndex");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.AlbumParsedEventEntity", b =>
                {
                    b.HasOne("MetalReleaseTracker.ParserService.Infrastructure.Data.Entities.ParsingSessionEntity", "ParsingSession")
                        .WithMany()
                        .HasForeignKey("ParsingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParsingSession");
                });

            modelBuilder.Entity("MetalReleaseTracker.ParserService.Domain.Models.Entities.BandReferenceEntity", b =>
                {
                    b.Navigation("Discography");
                });
#pragma warning restore 612, 618
        }
    }
}
